fixtures:
  repositories:
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: 'v5.2.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: 'v8.1.0'
    zypprepo:
      repo: 'https://github.com/voxpupuli/puppet-zypprepo.git'
      ref: 'v4.0.1'
    yumrepo:
      repo: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core.git'
      ref: 'v1.1.0'
      puppet_version: ">= 6.0.0"
  symlinks:
    vmware: "#{source_dir}"
