fixtures:
  repositories:
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
      ref: '1.4.2'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.4.2'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '5.2.0'
    zypprepo:
      repo: 'https://github.com/voxpupuli/puppet-zypprepo.git'
      ref: 'v2.2.2'
    yumrepo:
      repo: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core.git'
      ref: '1.0.1'
      puppet_version: ">= 6.0.0"
  symlinks:
    vmware: "#{source_dir}"
