fixtures:
  repositories:
    apt:
      repo: 'git://github.com/puppetlabs/puppetlabs-apt.git'
      ref: '1.4.2'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
    zypprepo:
      repo: 'git://github.com/deadpoint/puppet-zypprepo.git'
  symlinks:
    vmware: "#{source_dir}"
