name    'emahags-vmware'
version '0.1.0'
source 'UNKNOWN'
author 'emahags'
license 'Apache License, Version 2.0'
summary 'Manage VMware'
description 'Manage VMware - Install vmwaretools'
project_page 'UNKNOWN'
